# Generated by Django 5.2.5 on 2025-08-28 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_sku', models.CharField(max_length=100, unique=True)),
                ('model_category', models.CharField(max_length=100)),
                ('model_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('model_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('other_specifications', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('imei_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stock_in_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned'), ('sold', 'Sold'), ('returned', 'Returned')], default='in_stock', max_length=20)),
                ('last_assigned_date', models.DateField(blank=True, null=True)),
                ('date_since_stock_in', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_added', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_assigned', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sales_process.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added to stock'), ('assigned', 'Assigned to user'), ('returned', 'Returned to stock'), ('sold', 'Sold'), ('status_change', 'Status Change')], max_length=50)),
                ('performed_on', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_history_actions', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales_process.stock')),
            ],
        ),
    ]
