# Generated by Django 5.2.5 on 2025-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
