# Generated by Django 5.2.5 on 2025-08-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_category',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('watch', 'Watch')], default='phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_ram',
            field=models.CharField(blank=True, choices=[('4gb', '4GB'), ('8gb', '8GB'), ('16gb', '16GB'), ('32gb', '32GB'), ('64gb', '64GB'), ('128gb', '128GB'), ('256gb', '256GB'), ('512gb', '512GB'), ('1tb', '1TB')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_storage',
            field=models.CharField(blank=True, choices=[('16gb', '16GB'), ('32gb', '32GB'), ('64gb', '64GB'), ('128gb', '128GB'), ('256gb', '256GB'), ('512gb', '512GB'), ('1tb', '1TB')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='network',
            field=models.CharField(blank=True, choices=[('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('5g', '5G')], max_length=100, null=True),
        ),
    ]
