# Generated by Django 5.2.5 on 2025-09-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0005_customer_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='sales_process.stock'),
        ),
    ]
