# Generated by Django 5.2.5 on 2025-09-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0006_sale_is_returned_sale_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
