# Generated by Django 5.2.5 on 2025-09-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0007_sale_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
