# Generated by Django 5.2.5 on 2025-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0009_stock_allocated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], max_length=255, null=True),
        ),
    ]
