# Generated by Django 5.2.5 on 2025-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_profile_date_of_joining_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('---', '---')], max_length=20, null=True),
        ),
    ]
