# Generated by Django 5.2.5 on 2025-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
