# Generated by Django 5.2.5 on 2025-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0006_alter_profile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
